const express = require("express");
const path = require("path");

// Create an Express server
const app = express();

// Serve static files from the 'dist' directory (generated by `npm run build`)
const staticPath = path.join(__dirname, "dist");
app.use(express.static(staticPath));

// Handle SPA routing (redirect all unmatched routes to index.html)
app.get("*", (req, res) => {
    res.sendFile(path.join(staticPath, "index.html"));
});

// Set the port to use environment variable PORT or default to 8080
const PORT = process.env.PORT || 8080;

// Start the server
app.listen(PORT, () => {
    console.log(`Server is running on http://localhost:${PORT}`);
});
